version: '2'
services:
  app:
    image: maven:3.8.3-openjdk-17
    container_name: mouse-maps-api
    volumes:
      - ./target:/usr/src/mouse-maps/target
      - .:/usr/src/mouse-maps
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app